import { GoogleGenAI } from "@google/genai";

/**
 * Service to interact with Gemini API for the AI Co-Pilot Advisor.
 */
export async function generateCoPilotResponse(
  userMessage: string,
  currentRole: string,
  targetRole: string
): Promise<string> {
  const apiKey = (import.meta as any).env?.VITE_GEMINI_API_KEY || "";

  // Dynamic system instruction tailored for the elite tech career coach with the critical safety rule
  const systemInstruction = `You are the CareerPilot AI Advisor, an elite tech career coach. The user is currently a [${currentRole}] aiming to transition into a [${targetRole}] role. 

CRITICAL SAFETY RULE: You are strictly a career guidance and technical resume mentor. First, evaluate if the user's incoming message [${userMessage}] is relevant to career growth, engineering leadership, software architecture, technical skills, job hunting, or workplace advice. 
- If the message is completely irrelevant or out-of-scope (e.g., asking about movies, sports, food, generic gossip, etc.), you MUST politely decline and steer them back on track. For example: 'I'm focused on helping you scale your career trajectory—let's keep our focus locked on your technical growth and professional path! Feel free to ask me anything about your engineering goals.'
- If the message is relevant, directly and intelligently answer their specific question with highly actionable, context-driven tips using clean Markdown format. Never use the repetitive Tech Lead placeholder response templates unless it directly answers what they asked.`;

  // Robust check: if VITE_GEMINI_API_KEY is configured on client side, call Gemini directly.
  if (apiKey && apiKey.trim() !== "" && !apiKey.includes("YOUR_API_KEY")) {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: userMessage,
        config: {
          systemInstruction,
        },
      });

      return response.text || "No response was generated by the AI Advisor.";
    } catch (err: any) {
      console.warn("Client-side direct Gemini call failed, falling back to backend API:", err.message || err);
    }
  }

  // Fallback: If VITE_GEMINI_API_KEY is missing/invalid or client call fails, call the backend API endpoint
  try {
    const response = await fetch("/api/career/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messages: [{ role: "user", content: userMessage }],
        currentRole,
        targetRole,
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      throw new Error(errData.error || "Failed to get AI advisor response from backend.");
    }

    const data = await response.json();
    return data.text || "I was unable to formulate a response. Please try again later.";
  } catch (err: any) {
    console.error("AI Advisor backend call failed:", err);
    throw new Error(err.message || "Failed to communicate with AI co-pilot");
  }
}
